version: '3.8'

services:
  kadark-quiz:
    build: .
    container_name: kadark_quiz_app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - quiz_storage:/app/public/data/quizzes

volumes:
  quiz_storage:
